server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
#          uri: https://git.oschina.net/gongxusheng/spring-config-demo.git
          uri: https://github.com/z6165039/spring-cloud-config.git
          searchPaths: my-sample-config